services:
  base:
    image: base
    build:
      context: .
      dockerfile: docker/base/Dockerfile

  caddy-webserver:
    depends_on: [base]
    image: caddy-webserver
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/caddy-webserver/Dockerfile
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/docker/caddy-webserver/Caddyfile:/etc/caddy/Caddyfile

  backend:
    depends_on: [base]
    image: backend
    restart: always
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - '3333:3333'

volumes:
  caddy_data:
    external: true
  caddy_config:
