on:
  push:
    branches:
      - production

name: Deploy to production

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy
        with:
          REMOTE_HOST: ${{ secrets.EC2_PRODUCTION_HOST }}
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu
          APP_DIRECTORY_NAME: ${{ github.event.repository.name }}
          TRANSCRYPT_KEY: ${{ secrets.TRANSCRYPT_KEY }}
          SSH_KEY: ${{ secrets.EC2_PRODUCTION_SSH_KEY }}
